a
git-svn-id: file:///raid/svn-personal/newsdist/trunk@14 6619d122-1e26-ed48-a79d-fd80d44ec7e7

diff --git a/Maintainer/indent b/Maintainer/indent
--- a/Maintainer/indent
+++ b/Maintainer/indent
@@ -3,11 +3,20 @@
 
 . ./Maintainer/tools.sh
 
+ERRORS=0
 for i in $DIRS; do
 	echo "--- $i"
 	for j in `ls -d $i/*.c $i/*.h 2>/dev/null`; do
 		echo "----- $j"
 		indent -npro -lpl -lp -bbb -bad -nfbs $j
+		if [ ! "$?" = "0" ]; then
+			ERRORS=$(($ERRORS + 1))
+		fi
 	done
 done
 rm -f *.BAK
+echo
+echo "$ERRORS error(s)"
+if [ "$ERRORS" -gt 0 ]; then
+	exit 1
+fi
