format
git-svn-id: file:///raid/svn-personal/newsdist/trunk@195 6619d122-1e26-ed48-a79d-fd80d44ec7e7

diff --git a/Maintainer/indent b/Maintainer/indent
--- a/Maintainer/indent
+++ b/Maintainer/indent
@@ -3,6 +3,27 @@
 
 . ./Maintainer/tools.sh
 
+ERRORS=0
+for i in $DIRS; do
+	echo "--- $i"
+	for j in `list $i` `list_header $i`; do
+		echo "----- $j"
+		clang-format -i $j
+		if [ ! "$?" = "0" ]; then
+			ERRORS=$(($ERRORS + 1))
+		fi
+	done
+done
+echo
+echo "$ERRORS error(s)"
+if [ "$ERRORS" -gt 0 ]; then
+	exit 1
+fi
+
+exit 0
+
+### OBSOLETE CODE ###
+
 indent --version | grep GNU >/dev/null 2>&1
 if [ "$?" = "0" ]; then
 	ORIG="-orig"
